services:
  web:
    build: .
    command: sh start.sh
    volumes:
      - .:/app
      - staticfiles:/app/staticfiles  # Mount staticfiles volume
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: mssql_server
    environment:
      SA_PASSWORD: "${MSSQL_PASSWORD}"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql

volumes:
  mssql_data:
  staticfiles:  # Named volume for static files